# sqlite usage
version: '3'

services:
  chatapi:
    build: ./
    restart: always
    environment:
      NODE_ENV: production
      IS_USE_SQLITE: 'true'
      # DB_HOSTNAME: ${localip}
      # DB_NAME: chat-api
      # DB_USERNAME: root
      # DB_PASSWORD: rootpass
      PORT: 3030
    volumes:
      - ./chatapi.sqlite/:/app/chatapi.sqlite
    ports:
      - 3030:3030
    # command: npm start
